loader:
    maxSize: 10
    maxWaitSeconds: 20
consumerGroups:
    -
        groupID: db-batcher
        topicRegexes: "tipocaprefix.dbname.table1, tipocaprefix.dbname.table2"
        loaderTopicPrefix: loader-
        kafka:
            brokers: "localhost:9092, localhost:9094"
            version: "2.5.0"
            kafkaClient: "sarama"
        sarama:
            assignor: "range"
            oldest: true
            log: false
            autoCommit: false
schemaRegistryURL: "https://schema-registry.example.com"
s3sink:
    region: "us-west-1"
    accessKeyId: "sample-aws-access-key-id"
    secretAccessKey: "sample-secret-access-key"
    bucket: "docker-vault"
    bucketDir: "tipoca-stream-redshiftsink"
redshift:
    schema: "schema-to-operate-on"
    tableSuffix: ""
    host: "sample-host"
    port: "sample-port"
    database: "sample-database"
    user: "sample-redshift-user"
    password: "sample-password"
    timeout: 10
    s3AccessKeyId: "sample-s3-access-key"
    s3SecretAccessKey: "sample-secret-key"
    stats: false
    maxOpenConns: 0 # i.e. no limit
    maxIdleConns: 2 # default in go1.1
