apiVersion: v1
data:
  dbconfig.yaml: |-
    database.hostname: mysql-debezium
    database.port: 3306
    database.user: debezium
    database.password: dbz
    database.server.id: 184094
    database.server.name: dbserver1
    database.whitelist: inventory
    database.history.kafka.bootstrap.servers: k8s-kafka-bootstrap.kafka:9092
    database.history.kafka.topic: schema-changes.inventory
kind: ConfigMap
metadata:
  name: connector-configmap
