apiVersion: v1
kind: Service
metadata:
  labels:
    dependent: "true"
  name: mysql-debezium
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32366
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-debezium
  type: NodePort
