language: go
services:
  - docker
script:
- cd kafka-go
- make build
- test -f bin/linux_amd64/redshiftbatcher
- test -f bin/linux_amd64/redshiftloader
- make all-container
- docker images | grep "^practodev/redshiftbatcher"
- docker images | grep "^practodev/redshiftloader"
- make test
