apiVersion: tipoca.k8s.practo.dev/v1
kind: RedshiftSink
metadata:
  name: inventory
spec:
  secretRefName: redshfitsink-secret-2bh89m59ct
  secretRefNamespace: kube-system
  kafkaBrokers: "kafka1.example.com,kafka2.example.com"
  kafkaVersion: "2.6.0"
  kafkaTopicRegexes: "^db.inventory*"
  kafkaLoaderTopicPrefix: "loader-"
  releaseCondition:
    maxBatcherLag: 100
    maxLoaderLag: 10
  batcher:
    suspend: false
    mask: true
    maskFile: "https://github.com/practo/tipoca-stream/redshiftsink/pkg/transformer/masker/database.yaml"
    sinkGroup:
        all:
            maxSizePerBatch: 10Mi
            maxWaitSeconds: 30
            podTemplate:
              resources:
                requests:
                  cpu: 100m
                  memory: 200Mi
  loader:
    suspend: false
    redshiftSchema: "inventory"
    redshiftGroup:  "sales"
    sinkGroup:
        all:
            maxSizePerBatch: 1Gi
            maxWaitSeconds: 30
            podTemplate:
              resources:
                requests:
                  cpu: 100m
                  memory: 200Mi
