apiVersion: tipoca.k8s.practo.dev/v1
kind: RedshiftSink
metadata:
  name: inventory
spec:
  secretRefName: redshiftsink-secret-585g5m8t9h
  secretRefNamespace: kube-system
  batcher:
    suspend: false
    maxSize: 10
    maxWaitSeconds: 30
    mask: true
    maskConfigDir: "/"
    maskConfigFileName: "mask_config.yaml"
    kafkaBrokers: "kafka1.example.com,kafka2.example.com"
    kafkaGroup: "inventory-batcher"
    kafkaTopicRegexes: "^ts.inventory*"
    kafkaLoaderTopicPrefix: "loader-"
    podTemplate:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
  loader:
    suspend: false
    maxSize: 10
    maxWaitSeconds: 30
    kafkaBrokers: "kafka1.example.com,kafka2.example.com"
    kafkaGroup: "inventory-batcher"
    kafkaTopicRegexes: "^ts.inventory*"
    redshiftSchema: "inventory"
    podTemplate:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
