apiVersion: tipoca.k8s.practo.dev/v1
kind: RedshiftSink
metadata:
  name: inventory
spec:
  secretRefName: redshfitsink-secret-2bh89m59ct
  secretRefNamespace: kube-system
  kafkaBrokers: "kafka1.example.com,kafka2.example.com"
  kafkaVersion: "2.6.0"
  kafkaTopicRegexes: "^db.inventory*"
  kafkaLoaderTopicPrefix: "loader-"
  releaseCondition:
    maxBatcherLag: 100
    maxLoaderLag: 10
  batcher:
    suspend: false
    maxSize: 10
    maxWaitSeconds: 30
    mask: true
    maskFile: "https://github.com/practo/tipoca-stream/redshiftsink/pkg/transformer/masker/database.yaml"
    podTemplate:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
  loader:
    suspend: false
    maxSize: 10
    maxWaitSeconds: 30
    redshiftSchema: "inventory"
    redshiftGroup:  "sales"
    podTemplate:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
