apiVersion: v1
kind: Service
metadata:
  labels:
    app: redshiftsink-operator
  name: redshiftsink-operator
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: redshift-metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: redshiftsink-operator
  sessionAffinity: None
  type: ClusterIP
