apiVersion: v1
kind: Service
metadata:
  labels:
    app: redshiftsink-operator
  name: redshiftsink-operator
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: redshiftsink-operator
