# permissions for end users to view redshiftsinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redshiftsink-viewer-role
rules:
- apiGroups:
  - redshiftsinks
  resources:
  - redshiftsinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redshiftsinks
  resources:
  - redshiftsinks/status
  verbs:
  - get
