# permissions for end users to edit redshiftsinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redshiftsink-editor-role
rules:
- apiGroups:
  - redshiftsinks
  resources:
  - redshiftsinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redshiftsinks
  resources:
  - redshiftsinks/status
  verbs:
  - get
