- op: replace
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/batcher/properties/podTemplate/properties/spec/properties/initContainers/items/properties/ports/items/required
  value:
  - containerPort
  - protocol

- op: replace
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/batcher/properties/podTemplate/properties/spec/properties/containers/items/properties/ports/items/required
  value:
  - containerPort
  - protocol
