batcher:
    maxSize: 10
    maxWaitSeconds: 20
kafka:
    brokers: "localhost:9092, localhost:9094"
    group: "dbname"
    version: "2.5.0"
    topicPrefixes: "tipocaprefix.dbname.table1, tipocaprefix.dbname.table2"
    kafkaClient: "sarama"
sarama:
    assignor: "range"
    oldest: true
    log: false
s3sink:
    region: "us-west-1"
    accessKeyId: "sample-aws-access-key-id"
    secretAccessKey: "sample-secret-access-key"
    bucket: "docker-vault"
    bucketDir: "tipoca-stream-redshiftsink"
schemaRegistryURL: "https://schema-registry.practodev.com"
