batcher:
    mask: false
    maskSalt: sample-salt
    maskFile: /mask.yaml
    maskFileVersion: ''
    maxSize: 10
    maxWaitSeconds: 20
consumerGroups:
    -
        groupID: db-batcher
        topicRegexes: 'tipocaprefix.dbname.table1, tipocaprefix.dbname.table2'
        loaderTopicPrefix: loader-
        kafka:
            brokers: 'localhost:9092, localhost:9094'
            version: 2.5.0
            kafkaClient: sarama
        sarama:
            assignor: range
            oldest: true
            log: false
            autoCommit: true
s3sink:
    region: us-west-1
    accessKeyId: sample-aws-access-key-id
    secretAccessKey: sample-secret-access-key
    bucket: docker-vault
    bucketDir: tipoca-stream-redshiftsink
schemaRegistryURL: 'https://schema-registry.example.com'
gitAccessToken: 748abcdefghijklmnopqrstuvwxyz
