apiVersion: v1
kind: ServiceAccount
metadata:
  name: redshiftsink-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: redshiftsink-controller-manager
 namespace: kube-system
 labels:
   app: redshiftsink-controller-manager
spec:
 replicas: 1
 selector:
   matchLabels:
     app: redshiftsink-controller-manager
 template:
   metadata:
     labels:
       app: redshiftsink-controller-manager
   spec:
     serviceAccountName: redshiftsink-controller-manager
     tolerations:
     - effect: NoExecute
       operator: Exists
     - effect: NoSchedule
       operator: Exists
     volumes:
     - name: redshiftsink-secret-volume
       secret:
         secretName: redshiftsink-secret
     containers:
     - name: manager
       image: practodev/redshiftsink:latest
       imagePullPolicy: Always
       volumeMounts:
       - name: redshiftsink-secret-volume
         mountPath: /secret.yaml
       command:
       - /redshiftsink
       resources:
         limits:
           cpu: 100m
           memory: 100Mi
         requests:
           cpu: 10m
           memory: 20Mi
