apiVersion: v1
kind: ServiceAccount
metadata:
  name: redshiftsink-operator
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: redshiftsink-operator
 namespace: kube-system
 labels:
   app: redshiftsink-operator
spec:
 replicas: 1
 selector:
   matchLabels:
     app: redshiftsink-operator
 template:
   metadata:
     labels:
       app: redshiftsink-operator
   spec:
     serviceAccountName: redshiftsink-operator
     tolerations:
     - effect: NoExecute
       operator: Exists
     - effect: NoSchedule
       operator: Exists
     volumes:
     - name: redshiftsink-secret-volume
       secret:
         secretName: redshiftsink-secret
     containers:
     - name: manager
       image: 746161288457.dkr.ecr.ap-south-1.amazonaws.com/redshiftsink:latest
       imagePullPolicy: Always
       volumeMounts:
       - name: redshiftsink-secret-volume
         mountPath: /secret.yaml
       command:
       - /redshiftsink
       args:
       - --default-batcher-image="746161288457.dkr.ecr.ap-south-1.amazonaws.com/redshiftbatcher:latest"
       - --default-loader-image="746161288457.dkr.ecr.ap-south-1.amazonaws.com/redshiftloader:latest"
       - -v=2
       resources:
         limits:
           cpu: 100m
           memory: 100Mi
         requests:
           cpu: 10m
           memory: 20Mi
