non_pii_keys:
    customers:
    - id
    justifications:
    - source
    - type
    - createdAt
    - updatedAt
conditional_non_pii_keys:
    customers:
        email:
        - '%example.com'
        - '%exampledev.com'
dependent_non_pii_keys:
    customers:
        # dependentColumnName
        first_name:
            # providerColumn
            last_name:
            - 'Jones'
            - 'Dhoni'
length_keys:
    customers:
    - email
sort_keys:
    customers:
    - id
    justifications:
    - createdAt
dist_keys:
    customers:
    - email
    justifications:
    - source
