non_pii_keys:
    customers:
    - id
    justifications:
    - source
    - type
    - createdAt
    - updatedAt
conditional_non_pii_keys:
    justifications:
        justice:
        - 'mahatma'
        # test for case insensitivity
        Reason:
        - 'want'
    customers:
        email:
        - '%example.com'
        - '%exampledev.com'
dependent_non_pii_keys:
    justifications::
        # test for case insensitivity
        Justice:
            # test for case insensitivity
            Reason:
            - 'want'
    customers:
        # dependentColumnName
        first_name:
            # providerColumn
            last_name:
            - 'Jones'
            - 'Dhoni'
length_keys:
    customers:
    - email
mobile_keys:
    customers:
    - mobile_number
sort_keys:
    customers:
    - id
    justifications:
    - createdAt
dist_keys:
    customers:
    - email
    justifications:
    - source
