
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: redshiftsink-operator
  name: redshiftsink-operator
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
    - path: /metrics
      port: redshift-metrics
  selector:
    matchLabels:
      app: redshiftsink-operator
